### ISSUE TITLE
Wrong number of arguments to send_error_response!

### ISSUE THREAD

**Issue by sodabrew** [brightroll/unixrack#8]
This line is incorrect. I'll submit a fix shortly. Thanks to @bwitt for reporting.

https://github.com/brightroll/unixrack/blob/master/unixrack.rb#L364

**Comment by sodabrew** [comment]
https://github.com/drudru/unixrack/pull/1

**Comment by sodabrew** [comment]
The branch v1.0.4.1 has this and two other fixes, built a temporary gem for internal use.

**Comment by drudru** [comment]
Hi - will pull this week - thanks guys!

**Comment by sodabrew** [comment]
Thanks Dru! Looking forward to an update on rubygems.org :)
Commit log of the stuff I put into the internal 1.0.4.1: https://github.com/brightroll/unixrack/commits/v1.0.4.1

**Comment by sodabrew** [comment]
Resolved, thanks @drudru !

**Comment by drudru** [comment]
Thank you guys!
